name: strtech-phabricator
description: |
  使用IP地址 [10.42.2.2, 10.42.2.3] 请维护者做好规划
version: 1.0.0 # Version of the Catalog to be used
category: Stringstech # Category to be used for searching catalog entries
maintainer: tangxuyao # The maintainer of the catalog entry
# license: # The license
# projectURL: # A URL related to the catalog entry
