version: '2'
catalog:
  name: "elasticsearch" # Name of the versioned template of the Catalog Entry
  version: "6.1.2-stringstech" # Version of the versioned template of the Catalog Entry
  description: |
    filebeat默认设置如下:
    filebeat.prospectors:
    - type: log
      enabled: true
      paths:
        - /opt/log/*.log
    logging.level: debug

  #uuid: # Unique identifier to be used for upgrades. Please see note.
  #minimum_rancher_version: # The minimum version of Rancher that supports the template
  questions: #Used to request user input for configuration options
#    - variable: "password"
#      required: true
#      description: "elasticsearch 密码"
#      label: "密码"
#      type: "string"
#      default: "stringstech"
#    - variable: "logstash_yml"
#      required: true
#      description: "yml configs"
#      label: "yml配置文件内容:"
#      default: |
#        http.host: "0.0.0.0"
#        path.config: /usr/share/logstash/pipeline
#        xpack.monitoring.elasticsearch.url: http://elasticsearch:9200
#        xpack.monitoring.elasticsearch.username: logstash_system
#        xpack.monitoring.elasticsearch.password: changeme
#      type: "multiline"
    - variable: "logstash_configs"
      required: true
      description: "logstash all config"
      label: "logstash config"
      default: |
        input {
          beats {
            port => 5044
          }
        }

        filter {
          json {
            source => "message"
          }
        }

        output {
          elasticsearch {
            hosts => ["elasticsearch:9200"]
          }
        }
      type: "multiline"
    - variable: "filebeat_hosts"
      type: "string"
      required: true
      description: "设置主机地址，例如: logstash:5044, 10.0.1.112:5000"
      label: "设置主机地址"
      default: logstash:5044
    - variable: "filebeat_paths"
      type: "string"
      required: true
      label: "指定日志路径"
      description: "指定日志路径"
      default: /opt/log/*log

logstash:
  metadata:
    logstash:
      configs: |
        ${logstash_configs}
#      yml: |
#        ${logstash_yml}
filebeat:
  metadata:
    fb:
      hosts: |
        ${filebeat_hosts}
      paths: |
        ${filebeat_paths}

# 不能加入如下语句，会导致生成配置文件失败.
#version: '2'
#services:
#  elasticsearch-master:
#    retain_ip: true
#    scale: 1
#    start_on_create: true
#    health_check:
#      healthy_threshold: 2
#      response_timeout: 2000
#      port: 9200
#      unhealthy_threshold: 3
#      initializing_timeout: 60000
#      interval: 2000
#      strategy: recreate
#      reinitializing_timeout: 60000