version: '2.2'
services:
  elasticsearch-master:
    image: docker.elastic.co/elasticsearch/elasticsearch-platinum:6.1.1
    labels:
      io.rancher.container.hostname_override: container_name
    environment:
      - cluster.name=stringstech-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${password}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

volumes:
  esdata:
    driver: local