version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '3306:3306'
    volumes:
      - 'mariadb_data:/bitnami'
  phabricator:
    image: 'bitnami/phabricator:latest'
    labels:
      kompose.service.type: nodeport
      io.rancher.container.requested_ip: 10.42.2.2
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'phabricator_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - PHABRICATOR_HOST=10.42.2.2
      - PHABRICATOR_EMAIL=daulgas.tang@stringstech.co
      - PHABRICATOR_USERNAME=admin
      - PHABRICATOR_PASSWORD=taNg##85718
      - PHABRICATOR_FIRSTNAME=tang
      - PHABRICATOR_LASTNAME=xuyao
      - SMTP_HOST=smtp.office365.com
      - SMTP_PORT=587
      - SMTP_USER=noreply@stringstech.co
      - SMTP_PASSWORD=Bucu0421

volumes:
  mariadb_data:
    driver: local
  phabricator_data:
    driver: local
