name: strtech-proxy
description: |
  反向代理服务器
version: 1.0.0 # Version of the Catalog to be used
category: Stringstech # Category to be used for searching catalog entries
maintainer: tangxuyao # The maintainer of the catalog entry
# license: # The license
# projectURL: # A URL related to the catalog entry
