version: '2'
services:
  elasticsearch-master:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    stdin_open: true
    tty: true
    environment:
      - cluster.name=stringstech-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200
#      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.1
    stdin_open: true
    tty: true
    links:
      - elasticsearch-master:elasticsearch
    ports:
      - 5601:5601/tcp
    labels:
      io.rancher.container.pull_image: always

volumes:
  esdata:
    driver: local